export const usuarios = [
  // ================= COMANDANTE =================
  { id: 1, nombre: 'Zarbon Elite', rol: 'Comandante', nivel_poder: 18000 },
  { id: 2, nombre: 'Dodoria Magna', rol: 'Comandante', nivel_poder: 22000 },
  { id: 3, nombre: 'Cui Rex', rol: 'Comandante', nivel_poder: 25000 },
  { id: 4, nombre: 'Appule Prime', rol: 'Comandante', nivel_poder: 19000 },
  { id: 5, nombre: 'Orlen Vex', rol: 'Comandante', nivel_poder: 21000 },
  { id: 6, nombre: 'Nappa Shade', rol: 'Comandante', nivel_poder: 23000 },
  { id: 7, nombre: 'Recoome Crest', rol: 'Comandante', nivel_poder: 20000 },
  { id: 8, nombre: 'Burter Flash', rol: 'Comandante', nivel_poder: 24000 },
  { id: 9, nombre: 'Jeice Blaze', rol: 'Comandante', nivel_poder: 17000 },
  { id: 10, nombre: 'Guldo Mind', rol: 'Comandante', nivel_poder: 26000 },
  { id: 11, nombre: 'Salza Arc', rol: 'Comandante', nivel_poder: 22500 },
  { id: 12, nombre: 'Neiz Storm', rol: 'Comandante', nivel_poder: 19500 },
  { id: 13, nombre: 'Doore Crush', rol: 'Comandante', nivel_poder: 21500 },
  { id: 14, nombre: 'Zangya Flow', rol: 'Comandante', nivel_poder: 23500 },
  { id: 15, nombre: 'Bujin Veil', rol: 'Comandante', nivel_poder: 20500 },

  // ================= ANALISTA =================
  { id: 16, nombre: 'Malaka Data', rol: 'Analista', nivel_poder: 4000 },
  { id: 17, nombre: 'Planthorr Scan', rol: 'Analista', nivel_poder: 4500 },
  { id: 18, nombre: 'Shisami Read', rol: 'Analista', nivel_poder: 3800 },
  { id: 19, nombre: 'Tagoma Calc', rol: 'Analista', nivel_poder: 5000 },
  { id: 20, nombre: 'Abo Trace', rol: 'Analista', nivel_poder: 4200 },
  { id: 21, nombre: 'Kado Map', rol: 'Analista', nivel_poder: 4700 },
  { id: 22, nombre: 'Raspberry Log', rol: 'Analista', nivel_poder: 3900 },
  { id: 23, nombre: 'Blueberry Chart', rol: 'Analista', nivel_poder: 4300 },
  { id: 24, nombre: 'Strawberry Net', rol: 'Analista', nivel_poder: 4600 },
  { id: 25, nombre: 'Cui Scan', rol: 'Analista', nivel_poder: 4100 },
  { id: 26, nombre: 'Orlen Map', rol: 'Analista', nivel_poder: 4800 },
  { id: 27, nombre: 'Appule Log', rol: 'Analista', nivel_poder: 3700 },
  { id: 28, nombre: 'Zeeun Read', rol: 'Analista', nivel_poder: 5100 },
  { id: 29, nombre: 'Medamatcha Parse', rol: 'Analista', nivel_poder: 4400 },
  { id: 30, nombre: 'Angila Flux', rol: 'Analista', nivel_poder: 4900 },

  // ================= DESARROLLADOR =================
  { id: 31, nombre: 'Frieza-Bot X1', rol: 'Desarrollador', nivel_poder: 6000 },
  { id: 32, nombre: 'Frieza-Bot X2', rol: 'Desarrollador', nivel_poder: 6500 },
  { id: 33, nombre: 'Mecha-Sys 7', rol: 'Desarrollador', nivel_poder: 5800 },
  { id: 34, nombre: 'Abo-Tech', rol: 'Desarrollador', nivel_poder: 7000 },
  { id: 35, nombre: 'Kado-Dev', rol: 'Desarrollador', nivel_poder: 6200 },
  { id: 36, nombre: 'Sorbet Build', rol: 'Desarrollador', nivel_poder: 6700 },
  { id: 37, nombre: 'Shisami Code', rol: 'Desarrollador', nivel_poder: 5900 },
  { id: 38, nombre: 'Tagoma Forge', rol: 'Desarrollador', nivel_poder: 6300 },
  { id: 39, nombre: 'Malaka Dev', rol: 'Desarrollador', nivel_poder: 6600 },
  { id: 40, nombre: 'Planthorr Lab', rol: 'Desarrollador', nivel_poder: 6100 },
  { id: 41, nombre: 'Wanta Core', rol: 'Desarrollador', nivel_poder: 6800 },
  { id: 42, nombre: 'Panta Stack', rol: 'Desarrollador', nivel_poder: 5700 },
  { id: 43, nombre: 'Kikono Build', rol: 'Desarrollador', nivel_poder: 7100 },
  { id: 44, nombre: 'Berryblue Dev', rol: 'Desarrollador', nivel_poder: 6400 },
  { id: 45, nombre: 'Mocco Stack', rol: 'Desarrollador', nivel_poder: 6900 },

  // ================= ESPECIALISTA =================
  { id: 46, nombre: 'Zarbon Field', rol: 'Especialista', nivel_poder: 9000 },
  { id: 47, nombre: 'Dodoria Ops', rol: 'Especialista', nivel_poder: 9500 },
  { id: 48, nombre: 'Jeice Spec', rol: 'Especialista', nivel_poder: 8800 },
  { id: 49, nombre: 'Recoome Ops', rol: 'Especialista', nivel_poder: 10000 },
  { id: 50, nombre: 'Burter Ops', rol: 'Especialista', nivel_poder: 9200 },
  { id: 51, nombre: 'Guldo Spec', rol: 'Especialista', nivel_poder: 9700 },
  { id: 52, nombre: 'Salza Field', rol: 'Especialista', nivel_poder: 8900 },
  { id: 53, nombre: 'Neiz Ops', rol: 'Especialista', nivel_poder: 9300 },
  { id: 54, nombre: 'Doore Field', rol: 'Especialista', nivel_poder: 9600 },
  { id: 55, nombre: 'Zangya Spec', rol: 'Especialista', nivel_poder: 9100 },
  { id: 56, nombre: 'Bujin Ops', rol: 'Especialista', nivel_poder: 9800 },
  { id: 57, nombre: 'Shisami Field', rol: 'Especialista', nivel_poder: 8700 },
  { id: 58, nombre: 'Tagoma Spec', rol: 'Especialista', nivel_poder: 10100 },
  { id: 59, nombre: 'Abo Field', rol: 'Especialista', nivel_poder: 9400 },
  { id: 60, nombre: 'Kado Ops', rol: 'Especialista', nivel_poder: 9900 },

  // ================= GESTOR =================
  { id: 61, nombre: 'Sorbet Admin', rol: 'Gestor', nivel_poder: 7000 },
  { id: 62, nombre: 'Tagoma Mgr', rol: 'Gestor', nivel_poder: 7500 },
  { id: 63, nombre: 'Shisami Ctrl', rol: 'Gestor', nivel_poder: 6800 },
  { id: 64, nombre: 'Malaka Mgr', rol: 'Gestor', nivel_poder: 8000 },
  { id: 65, nombre: 'Planthorr Adm', rol: 'Gestor', nivel_poder: 7200 },
  { id: 66, nombre: 'Kikono Mgr', rol: 'Gestor', nivel_poder: 7700 },
  { id: 67, nombre: 'Berryblue Ctrl', rol: 'Gestor', nivel_poder: 6900 },
  { id: 68, nombre: 'Mocco Adm', rol: 'Gestor', nivel_poder: 7300 },
  { id: 69, nombre: 'Wanta Mgr', rol: 'Gestor', nivel_poder: 7600 },
  { id: 70, nombre: 'Panta Ctrl', rol: 'Gestor', nivel_poder: 7100 },
  { id: 71, nombre: 'Raspberry Adm', rol: 'Gestor', nivel_poder: 7800 },
  { id: 72, nombre: 'Blueberry Mgr', rol: 'Gestor', nivel_poder: 6700 },
  { id: 73, nombre: 'Strawberry Ctrl', rol: 'Gestor', nivel_poder: 8100 },
  { id: 74, nombre: 'Zeeun Adm', rol: 'Gestor', nivel_poder: 7400 },
  { id: 75, nombre: 'Medamatcha Mgr', rol: 'Gestor', nivel_poder: 7900 },

  // ================= GUERRERO =================
  { id: 76, nombre: 'Nappa Rage', rol: 'Guerrero de Conquista', nivel_poder: 15000 },
  { id: 77, nombre: 'Raditz Storm', rol: 'Guerrero de Conquista', nivel_poder: 16000 },
  { id: 78, nombre: 'Turles Blade', rol: 'Guerrero de Conquista', nivel_poder: 14000 },
  { id: 79, nombre: 'Slug Fist', rol: 'Guerrero de Conquista', nivel_poder: 17000 },
  { id: 80, nombre: 'Cooler Strike', rol: 'Guerrero de Conquista', nivel_poder: 15500 },
  { id: 81, nombre: 'Bojack Crush', rol: 'Guerrero de Conquista', nivel_poder: 16500 },
  { id: 82, nombre: 'Bido Slash', rol: 'Guerrero de Conquista', nivel_poder: 14500 },
  { id: 83, nombre: 'Bujin Strike', rol: 'Guerrero de Conquista', nivel_poder: 17500 },
  { id: 84, nombre: 'Zangya Kick', rol: 'Guerrero de Conquista', nivel_poder: 15200 },
  { id: 85, nombre: 'Doore Smash', rol: 'Guerrero de Conquista', nivel_poder: 16200 },
  { id: 86, nombre: 'Neiz Crash', rol: 'Guerrero de Conquista', nivel_poder: 14200 },
  { id: 87, nombre: 'Salza Cut', rol: 'Guerrero de Conquista', nivel_poder: 17200 },
  { id: 88, nombre: 'Jeice Burn', rol: 'Guerrero de Conquista', nivel_poder: 15800 },
  { id: 89, nombre: 'Recoome Pound', rol: 'Guerrero de Conquista', nivel_poder: 16800 },
  { id: 90, nombre: 'Burter Rush', rol: 'Guerrero de Conquista', nivel_poder: 14800 },

  // ================= SCOUTER =================
  { id: 91, nombre: 'Scout-01', rol: 'Sistema Scouter', nivel_poder: 1000 },
  { id: 92, nombre: 'Scout-02', rol: 'Sistema Scouter', nivel_poder: 1200 },
  { id: 93, nombre: 'Scout-03', rol: 'Sistema Scouter', nivel_poder: 900 },
  { id: 94, nombre: 'Scout-04', rol: 'Sistema Scouter', nivel_poder: 1300 },
  { id: 95, nombre: 'Scout-05', rol: 'Sistema Scouter', nivel_poder: 1100 },
  { id: 96, nombre: 'Scout-06', rol: 'Sistema Scouter', nivel_poder: 1400 },
  { id: 97, nombre: 'Scout-07', rol: 'Sistema Scouter', nivel_poder: 950 },
  { id: 98, nombre: 'Scout-08', rol: 'Sistema Scouter', nivel_poder: 1250 },
  { id: 99, nombre: 'Scout-09', rol: 'Sistema Scouter', nivel_poder: 1050 },
  { id: 100, nombre: 'Scout-10', rol: 'Sistema Scouter', nivel_poder: 1350 },
  { id: 101, nombre: 'Scout-11', rol: 'Sistema Scouter', nivel_poder: 980 },
  { id: 102, nombre: 'Scout-12', rol: 'Sistema Scouter', nivel_poder: 1280 },
  { id: 103, nombre: 'Scout-13', rol: 'Sistema Scouter', nivel_poder: 1020 },
  { id: 104, nombre: 'Scout-14', rol: 'Sistema Scouter', nivel_poder: 1320 },
  { id: 105, nombre: 'Scout-15', rol: 'Sistema Scouter', nivel_poder: 1080 }
];